export const contactConstants ={
    GET_ALL_CONTACT_REQUEST : 'GET_ALL_CONTACT_REQUEST',
    GET_ALL_CONTACT_SUCCESS : 'GET_ALL_CONTACT_SUCCESS',
    GET_ALL_CONTACT_FAILURE : 'GET_ALL_CONTACT_FAILURE',


    ADD_CONTACT_REQUEST : 'ADD_CONTACT_REQUES',
    ADD_CONTACT_SUCCESS : 'ADD_CONTACT_SUCCESS',
    ADD_CONTACT_FAILURE : 'ADD_CONTACT_FAILURE',
      

    DELETE_CONTACT_REQUEST : 'DELETE_CONTACT_REQUES',
    DELETE_CONTACT_SUCCESS : 'DELETE_CONTACT_SUCCESS',
    DELETE_CONTACT_FAILURE : 'DELETE_CONTACT_FAILURE',


    EDIT_CONTACT_REQUEST : 'EDIT_CONTACT_REQUES',
    EDIT_CONTACT_SUCCESS : 'EDIT_CONTACT_SUCCESS',
    EDIT_CONTACT_FAILURE : 'EDIT_CONTACT_FAILURE',
}
